### ISSUE TITLE
Proposal: ignore ESLint for module.config.js file in @edx/frontend-build

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/frontend-wg#115]
As a consumer of `@edx/frontend-build`, I was getting ESLint warnings in my module.config.js file. However, this file is not code that gets shipped as part of any JS bundles to the end user and doesn't necessarily matter from a linting perspective. To eliminate erroneous linting errors that could arise in module.config.js, it might be worth adding module.config.js to ESLint's `ignorePatterns` so linting does not occur on this file.

**Comment by arbrandes** [comment]
@BilalQamar95, are you working on this?  Should we put this in the backlog for somebody else to pick up?

**Comment by BilalQamar95** [comment]
@arbrandes[ PR for this issue](https://github.com/openedx/frontend-build/pull/256) has been merged, this can be closed as completed
