### ISSUE TITLE
Add .nvmrc files to all frontend repositories

### ISSUE THREAD

**Issue by davidjoy** [openedx/frontend-wg#167]
An .nvmrc file is used by [nvm](https://github.com/nvm-sh/nvm) to determine what version of node a directory requires.  As we continue to upgrade our node versions, it's very helpful to let a tool like nvm automatically switch versions as you navigate between frontend codebases in your terminal.  Since the Node 12 -> 16 upgrade, some of us have found it very useful to ensure we're using the right version.  It's especially important for npm versions, as it prevents us from checking in package-lock.json files with the wrong schema version. 

The .nvmrc file generally contains something as simple as "18" to denote that the repo needs node 18.  nvm also manages installing the right npm version along with node.  

I'd advocate for adding .nvmrc files to all the frontend-* repos minimally, along with other legacy repos that run node. If someone isn't using nvm, the file is benign.

**Comment by adamstankiewicz** [comment]
@davidjoy We have been utilizing `.nvmrc` across pretty much the majority of our JS repos already through FED-BOM's Node 16/18 upgrade work, for example: [frontend-app-learning](https://github.com/openedx/frontend-app-learning/blob/master/.nvmrc), [frontend-app-profile](https://github.com/openedx/frontend-app-profile/blob/master/.nvmrc), [frontend-platform](https://github.com/openedx/frontend-platform/blob/master/.nvmrc), [frontend-build](https://github.com/openedx/frontend-build/blob/master/.nvmrc), [frontend-app-publisher](https://github.com/openedx/frontend-app-publisher/blob/master/.nvmrc), etc.

**Comment by adamstankiewicz** [comment]
Also worth noting, most of our Github Actions workflows for CI on PRs / commits now rely on `.nvmrc` to set the `NODE_VER` in the workflow ([example](https://github.com/openedx/frontend-app-publisher/blob/1e634e7fcd0f2160f653754ec6994b362569d24b/.github/workflows/ci.yml#L18-L19)). This also us to rely on the `.nvmrc` file as the source of truth for Node version in CI as well.

**Comment by davidjoy** [comment]
Yeah, @jmbowman and I were talking about it and realized it may not have been a blanket requirement, so we wanted to add this issue to make sure we made it ubiquitous. 😁

**Comment by abdullahwaheed** [comment]
done with node 18 upgrade
