### ISSUE TITLE
Frontend Header

### ISSUE THREAD

**Issue by ghassanmas** [openedx/frontend-wg#24]
Following our meeting on  #21 (19-OCT-21). 

This issue is intended to be as a reference and for discussion regarding the header component, it's intended to be used as a reference and to keep track of the logs todos..etc. 

### Background:
The learning MFE is currently is using its own hard-coded version of the headers because (maybe?) the learning app has a specific use case where the current frontend app component doesn't meet. While discussing this today, numerous suggestions/ideas were discussed (not decisions), for example, we could rebuild the component in a way where it would be customizable, extensible...etc

That being said before committing to how or what exactly should be done to resolve it, it would make sense to look over the cases in which how the MFE apps are using the headers.   

### To Do: 

- [ ] Document use cases of the headers in the MFE (in order to help create the path of the decision process of how the component should be an article). 

### Refs 
- Frontend app compoenet [repo](https://github.com/edx/frontend-component-header)
- Tne learning MFE [repo](https://github.com/edx/frontend-app-learning)
- Discussion about this issue at Mitx [issue](https://github.com/mitodl/mitxonline/issues/252)

**Comment by davidjoy** [comment]
I'm inclined to close out this issue in favor of https://github.com/openedx/build-test-release-wg/issues/81 where all the work seems to be happening.
