### ISSUE TITLE
Ensure `npm run build` is used in MFE repo build workflows

### ISSUE THREAD

**Issue by binodpant** [openedx/frontend-wg#33]
Why? Because some bugs don't get caught unless we actually build the prod build

- [ ] coordinate with arbi-bom to ensure the travis removal in favor of GH actions takes this into account (arbi-bom is helping)
- [x] @binodpant do this for all enterprise MFE repos
- [ ] TBD

**Comment by abdullahwaheed** [comment]
Created a google sheet to manage repos
https://docs.google.com/spreadsheets/d/1qME88h8SzZzJyPWvLCYW6Mkq-RCEJhVKNs_vv8U-E_I/edit?usp=sharing
