### ISSUE TITLE
Update enterprise MFEs to node16

### ISSUE THREAD

**Issue by binodpant** [openedx/frontend-wg#72]
For these repos

- enterprise learner portal :  https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/450 (JIRA: https://openedx.atlassian.net/browse/ENT-5502)
- enterprise admin portal : https://github.com/openedx/frontend-app-admin-portal/pull/695/
- enterprise public catalog : 
  - [ ] PR to add node matrix: https://github.com/openedx/frontend-app-enterprise-public-catalog/pull/198
  - [x] fix to unblock test failures in node16: https://github.com/openedx/frontend-app-enterprise-public-catalog/pull/199
- frontend-enterprise: https://github.com/openedx/frontend-enterprise/pull/210

**Comment by binodpant** [comment]
next step: this may not even be needed, will confirm with Arbi BOM on their plan of action first

**Comment by binodpant** [comment]
This can be edited slightly now to say just checking .nvmrc files, no need to update github workflow automation since ArbiBOM PRs will take care of that

Also revert the github workflow changes made priorly to use .nvmrc

**Comment by binodpant** [comment]
all repos have .nvmrc! with v12 in it for now. we will update this once arbiBOM has update the workflow files, just for local dev convenience

**Comment by binodpant** [comment]
to clarify: they all say v12 or 12 right now, this task is to ensure they get updated to v16 _after_ the arbiBOM steps has been completed

**Comment by binodpant** [comment]
I have reverted the .nvmrc changes in GH workflow files in the learner portal

now the remainder of this task is to track the actual enabling of node 16 for all the enterprise repos

**Comment by johnnagro** [comment]
This is all set, ready to close.
