### ISSUE TITLE
Update react-intl in frontend-platform

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-wg#75]
This will allow us to inject HTML/rich text into translated strings.  See [here](https://formatjs.io/docs/react-intl/components/#rich-text-formatting).

(Moved here from https://github.com/openedx/tcril-engineering/issues/3)

**Comment by adamstankiewicz** [comment]
This is now resolved in `@edx/frontend-platform@2.0.0`, where react-intl was upgraded to v5.
