### ISSUE TITLE
Build/track a list of repos to be updated

### ISSUE THREAD

**Issue by binodpant** [openedx/frontend-wg#77]
We will be using the same list as @adamstankiewicz has built for browserslist upgrades since this blocks that effort as well

https://docs.google.com/spreadsheets/d/1fduFbAxIbckiwHKNCtc41ImAL_CFIl9hZcC4AjDkuvI/edit#gid=0

**Comment by jmbowman** [comment]
I think this and pretty much every other ticket in the "node 16 upgrade" milestone is now complete.  Please verify, closing any issues in the milestone with no work left to be done.  If any of them do contain remaining work not already in progress, go ahead and start them.
