### ISSUE TITLE
frontend-build: moderate security vulnerability needs webpack-dev-server update

### ISSUE THREAD

**Issue by dianekaplan** [openedx/frontend-wg#82]
dependency chain: "@edx/frontend-build>webpack-dev-server>selfsigned>node-forge"

node-forge has a security vulnerability that's addressed in versions >=1.0.0. 

This is fixed in webpack-dev-server version 4.7.3, but frontend-build currently uses webpack-dev-server 4.6.0. We need to update webpack-dev-server

I've submitted a pull request for this issue here: https://github.com/openedx/frontend-build/pull/234

**Comment by jmbowman** [comment]
This was resolved in https://github.com/openedx/frontend-build/pull/234 .
